### ISSUE TITLE
Cannot instantiate TreeExplainer object when XGBoost model contains boosting tree with no split

### ISSUE THREAD

**Issue by Linh-nk** [mmschlk/shapiq#370]
I have an XGBoost model that works fine with the `shap` package but got this error message when trying to instantiate a Tree Explainer object.

```
File c:\Users\.venv\Lib\site-packages\shapiq\explainer\tree\base.py:104, in TreeModel.__post_init__(self)
    102 # setup max feature id
    103 if self.max_feature_id is None:
--> 104     self.max_feature_id = max(unique_features)
    105 # setup feature names
    106 if self.feature_ids is None:
```

After diagnosing, I realized it was because there are trees in my XGBoost model that has no split
For example, the code snippet below prints out `["Leaf"]`
```
for _, tree in final_model.get_booster().trees_to_dataframe().groupby('Tree'):
    print(np.unique(tree["Feature"].values))
```

**Comment by mmschlk** [comment]
I see, would you be able to post a small minimal example of this? I recon it's quite hard to reproduce this. :/

**Comment by Linh-nk** [comment]
Yes, it's hard to reliably reproduce the bug, but I could send you a pickle file of a trained XGBoost model that has trees with no split.

**Comment by jlopezpena** [comment]
I hit this when testing `shapiq` as a replacement for `shap` in my pipeline (as well as a bug with `pandas >= 2.0`, see below). Here is some code that will deterministically reproduce the bug:

The script trains a 3-class XGBClassifier on make_classification data (30 samples, 3 features, random_state=0) with `n_estimators=50`, `max_depth=2`, `learning_rate=0.5`, `n_jobs=1`. With this seed/config, 70 of the 150 boosting outputs are pure stumps — verified identical across 10 trial runs.

When passed to `shapiq.TreeExplainer, TreeModel.__post_init__` crashes at `max(unique_features)` exactly as the original report described.

Note: on pandas ≥ 2.0 the script first hits a separate bug in `convert_xgboost_booster (booster_df.loc[:, "Feature"] = booster_df["Feature"].replace(...)` raises `TypeError: Invalid value '[...]' for dtype 'str')`, so the repro inlines a one-line patch (.map(...).astype(int)) so #370 surfaces directly. That `.loc` line looks like a separate small fix worth landing alongside.

```python
"""Minimal reproducible example for mmschlk/shapiq#370.

  The XGBoost multi-class classifier below has 70 stump trees (out of 150
  boosting rounds * 3 classes), all driven by the seed and config below.
  Confirmed identical across 10 trial runs: stump count = 70/150.

  Trying to wrap the model with shapiq.TreeExplainer raises

      ValueError: max() iterable argument is empty

  from shapiq.explainer.tree.base.TreeModel.__post_init__ at
      self.max_feature_id = max(unique_features)

  because `unique_features` excludes the `Leaf` sentinel and is therefore empty
  for any tree with no splits.

  Versions:
      xgboost == 3.2.0
      shapiq  == 1.4.1
      numpy   == 2.3.x
      pandas  >= 2.0  (see the monkey-patch note below)

  Note for pandas 2.x:
      On pandas 2.x, this minimal repro is initially blocked by a *separate*
      bug in shapiq.explainer.tree.conversion.xgboost.convert_xgboost_booster:

          booster_df.loc[:, "Feature"] = booster_df["Feature"].replace(...)

      which raises `TypeError: Invalid value '[...]' for dtype 'str'` because
      pandas 2.x refuses to silently widen a str-dtype column to int. To make
      #370 surface, we patch that assignment to use `.map(...).astype(int)`
      inline below. This patch might itself be worth filling as a separate issue/PR.
  """

  import warnings

  from sklearn.datasets import make_classification
  from xgboost import XGBClassifier

  # ---------------------------------------------------------------------------
  # pandas-2.x compatibility patch for `convert_xgboost_booster`. Replace the
  # str-column -> int-array reassignment with a .map() + .astype(int). Without
  # this, the repro fails earlier with a different bug on pandas >= 2.0.
  # ---------------------------------------------------------------------------
  import shapiq.explainer.tree.conversion.xgboost as _xc
  import shapiq.explainer.tree.validation as _val


  def _patched_convert(tree_booster, class_label=None):
      try:
          intercept = tree_booster.base_score
          if intercept is None:
              intercept = float(tree_booster.intercept_[0])
          tree_booster = tree_booster.get_booster()
      except AttributeError:
          intercept = 0.0
      booster_df = tree_booster.trees_to_dataframe()
      feature_names = tree_booster.feature_names or [f"f{i}" for i in range(tree_booster.num_features())]
      name_to_idx = {k: v for v, k in enumerate(feature_names)}
      name_to_idx["Leaf"] = -2
      booster_df["Feature"] = booster_df["Feature"].map(name_to_idx).astype(int)
      if len(booster_df["Tree"].unique()) > tree_booster.num_boosted_rounds():
          n_class = int(len(booster_df["Tree"].unique()) / tree_booster.num_boosted_rounds())
          cls = 0 if class_label is None else class_label
          booster_df = booster_df.loc[booster_df["Tree"] % n_class == cls, :]
      n_trees = len(booster_df["Tree"].unique())
      intercept /= n_trees
      return [
          _xc._convert_xgboost_tree_as_df(tree_df=t, intercept=intercept, output_type="raw", scaling=1.0)
          for _, t in booster_df.groupby("Tree")
      ]


  _xc.convert_xgboost_booster = _patched_convert
  _val.convert_xgboost_booster = _patched_convert

  # ---------------------------------------------------------------------------
  # 1) Train a tiny multi-class XGBoost model that produces stump trees.
  # ---------------------------------------------------------------------------
  import shapiq  # noqa: E402  (imported after the patch on purpose)

  X, y = make_classification(
      n_samples=30,
      n_features=3,
      n_informative=3,
      n_redundant=0,
      n_classes=3,
      n_clusters_per_class=1,
      random_state=0,
  )
  X = X.astype("float32")

  with warnings.catch_warnings():
      warnings.simplefilter("ignore")
      model = XGBClassifier(
          n_estimators=50,
          max_depth=2,
          learning_rate=0.5,
          objective="multi:softprob",
          enable_categorical=False,
          verbosity=0,
          random_state=0,
          n_jobs=1,
      ).fit(X, y)

  # Confirm stumps are present (deterministic: 70 out of 150 with the seed above)
  booster_df = model.get_booster().trees_to_dataframe()
  splits_per_tree = booster_df.groupby("Tree").apply(
      lambda g: (g["Feature"] != "Leaf").sum(), include_groups=False
  )
  n_total = len(splits_per_tree)
  n_stumps = int((splits_per_tree == 0).sum())
  print(f"trees: {n_total}, stumps: {n_stumps}")
  assert n_total == 150 and n_stumps == 70, "non-deterministic - please report"

  # ---------------------------------------------------------------------------
  # 2) Trigger the #370 crash.
  # ---------------------------------------------------------------------------
  print("\n>>> shapiq.TreeExplainer(model=model, index='SV', max_order=1, class_index=0)")
  shapiq.TreeExplainer(model=model, index="SV", max_order=1, class_index=0)
```

**Comment by jlopezpena** [comment]
Update: testing on the head of main it seems that both issues are already fixed, sorry for the noise! Feel free to use my example as a regression test.

**Comment by Advueu963** [comment]
Hey jlopezpena,

Thank you for using shapiq, and we are sorry that we still have not fixed this error.

As good news, we are currently undergoing the tree fixes and hope to release v1.5.0 soon (latest end of next week).

This should address many of the current issues with the TreeExplainer.

Best regards,
Santo

**Comment by Advueu963** [comment]
Closed in #519
